### ISSUE TITLE
Add the track description column in the take browser

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#21]

**Comment by subirranjan1** [comment]
@omimo  Looks like the presentation of the data will exceed the space of the screen and it won't look good.Please reopen if you really want it or you have any other alternative.

**Comment by omimo** [comment]
The description can be very informative on the take browser. 
I think there are some workarounds for this: 
1. Remove the column for the Technician name to free up more space. 
2. Remove the column for the Recorded On date #22 
3. Make the description truncated proportionate to the available width, but have something like a [...] that when the user clicks on, the whole description is shown/popped up.

**Comment by subirranjan1** [comment]
Done
