### ISSUE TITLE
In the take browser, as the date is the same for all of the tracks it shouldn't be shown in the table

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#22]

**Comment by subirranjan1** [comment]
Done

**Comment by omimo** [comment]
The column is still there: 

![screenshot from 2016-02-20 16-37-17](https://cloud.githubusercontent.com/assets/581375/13200135/6b604d50-d7f0-11e5-87e9-5a252c60953a.png)

**Comment by subirranjan1** [comment]
Done
