### ISSUE TITLE
Optimize the column width of all of the data tables

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#23]
The size of the columns should be proportionat to the size of the texts

Things such as the name or description should take most of the space

Things that by definition have a fixed length should have the fixed column size (e.g., date)

**Comment by subirranjan1** [comment]
This is done.Please reopen if you would like to modify anything else.

**Comment by omimo** [comment]
Not exactly an issue with the column sizes, but can you please make the "Name" column content less truncated, or truncated proportionate to the available width?

**Comment by subirranjan1** [comment]
@omimo  Can you let me know page are you talking about with a screenshot mentioning the intentions?

**Comment by omimo** [comment]
I mean there is a lot of white space left, which can be used to display the more of the name: 

<img width="593" alt="screen shot 2016-02-21 at 9 51 06 pm" src="https://cloud.githubusercontent.com/assets/581375/13210573/952613c2-d8e5-11e5-9b9f-0ebaca4ea461.png">

**Comment by subirranjan1** [comment]
This is done.
