### ISSUE TITLE
Issues with Datatables :Filtering and Paging

### ISSUE THREAD

**Issue by subirranjan1** [michaelnixon/mm-file-support#3]
Datatable responds slow when lots of data

**Comment by subirranjan1** [comment]
@omimo  @michaelnixon  DataTable filtering takes time because while searching in data tracks page, every keystroke in the search box creates an ajax request, hence several ajax requests gets created when user only wants to do one search. A simple workaround of this is to create a search button which when clicked starts the search. Looking forward to develop that plugin. Any advice is welcome.

**Comment by michaelnixon** [comment]
Look into the data table setup; there may be an existing way to change whether it searches on every keystroke or not.

**Comment by subirranjan1** [comment]
@omimo  Hi, I fixed the data_tracks searching function as told above. But still I feel it takes a lot of time to search when table has large number of records.Basically the reason is joins of several tables. 

Just to update, I am figuring out a way to solve this (sphinx can be an option but is restricted to mysql). Have other ideas too and will test with them. Comments are appreciated.

**Comment by omimo** [comment]
Great!

**Comment by subirranjan1** [comment]
Removed the logic of ajax call on every key stroke. User need to click search button for searching.
