### ISSUE TITLE
Modifications to the logo/title area

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#31]
There are some comments from Philippe:
- Instead of the "M+M Movement Database", say "The Open Source Movement Database". This text should have the same font size as the "MoDa" in the logo.
- The "MoDa" text in the log should be aligned with the menu items. This means the menu bar should be lower. The logo might need to be a bit smaller.

**Comment by omimo** [comment]
Also, the left margin for the logo and the content should be a bit bigger. As in the design PDFs.

**Comment by subirranjan1** [comment]
@omimo  M+M Movement Database is written in the logo, hence logo needs to be changed with the new text as requested by @pasquier . @amkass  Request your comment on this.

I can adjust the menu bar to be lower once I get the new logo.
