### ISSUE TITLE
Look for color inconsistencies throughout the website

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#32]
Please make sure only the black, grey,  white, and red colors are used. 

Just some examples:
- The "Create Take/Project/..." buttons
- The number of takes in the Group Browser
- The notifications
- Sign in page

**Comment by subirranjan1** [comment]
@amkass  What is the color hex code used in logo? I am assuming I need to apply the same color to all the buttons and other places as @omimo  mentioned in his comment above.

**Comment by omimo** [comment]
Warnings, messages, etc.
