### ISSUE TITLE
Track browser search: Clean up the table

### ISSUE THREAD

**Issue by omimo** [michaelnixon/mm-file-support#54]
- Add track description
- Remove Technician and Tag
- If still slow, then remove the Mover

**Comment by subirranjan1** [comment]
@omimo @pasquier  Track browser loading and searching is faster now.However I had to remove sensor types as well.I have added take descriptions column too.All columns are searchable.Take Descriptions for Eye Tracking project have null values which will be fixed once we re import the data after compressing the video.Please reopen this issue in case you have any issues or want any modifications.
